version: "3.1"

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
       POSTGRES_DB: "test_db"
       POSTGRES_USER: "postgres"
       POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/12
    networks:
      - djangonetwork

  web:
    build: .
    container_name: web
    command:  bash -c "sleep 5 . venv/bin/activate && python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    ports:
      - 5000:5000
    networks:
      - djangonetwork
    depends_on:
      - db
    links:
      - db:db

volumes:
  db-data:

networks:
  djangonetwork:
