version: "3.1"

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./.database:/var/lib/postgresql/12
    networks:
      - djangonetwork
    healthcheck:
      test: [ "CMD", "pg_isready -d postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: web
    # command:  bash -c "sleep 4s; venv/bin/python3 manage.py migrate && venv/bin/python3 manage.py runserver 0.0.0.0:5000"
    command: ["bash", "entrypoint.sh"]
    env_file:
      - ./.env
    ports:
      - 8000:8000
    networks:
      - djangonetwork
    depends_on:
      - db
    links:
      - db:db

volumes:
  db-data:

networks:
  djangonetwork:
